name: Simple Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        uses: actions/checkout@v4

      - name: Step 2
        run: ls -la
        run: pwd
  
  job2:
    name: Second Job to run
    runs-on: windows-latest
    needs: job1

    steps:
      - name: Step one of  job2
        uses: actions/checkout@v4
      - name: Step two of job2
        run: pwd
